/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ReadRDashboardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/DashboardView.ts
var import_obsidian = require("obsidian");

// src/utils/constants.ts
var VIEW_TYPE_DASHBOARD = "readr-dashboard";
var STATUS_MAP = {
  "to-read": { tag: "to-read", label: "To Read", color: "var(--color-blue)", order: 0 },
  browsed: { tag: "browsed", label: "Browsed", color: "var(--color-green)", order: 1 },
  "close-read": { tag: "close-read", label: "Close Read", color: "var(--color-purple)", order: 2 },
  reviewed: { tag: "reviewed", label: "Reviewed", color: "var(--color-orange)", order: 3 }
};
var ALL_STATUSES = ["to-read", "browsed", "close-read", "reviewed"];
var DEFAULT_REFRESH_INTERVAL = 3e5;
var MAX_ACTIVITY_ITEMS = 10;
var RECENT_ACTIVITY_DAYS = 7;
var SYNTHESIS_THRESHOLD = 3;
var ENTRIES_PATH = '"library/entries"';
var ASSET_PATHS = {
  concepts: '"library/concepts"',
  authors: '"library/authors"',
  datasets: '"library/datasets"',
  benchmarks: '"library/benchmarks"'
};

// src/data/DataService.ts
var DataService = class {
  constructor(app) {
    this.app = app;
    this.dv = null;
    var _a;
    try {
      const dvPlugin = (_a = this.app.plugins) == null ? void 0 : _a.getPlugin("dataview");
      if (dvPlugin == null ? void 0 : dvPlugin.api) {
        this.dv = dvPlugin;
      }
    } catch (e) {
    }
  }
  /** Whether Dataview is available */
  get hasDataview() {
    return this.dv !== null;
  }
  /** Get all paper entries from library/entries */
  getAllPapers() {
    if (this.dv) {
      return this.getPapersFromDataview();
    }
    return this.getPapersFromMetadata();
  }
  /** Get papers filtered by status */
  getPapersByStatus(status) {
    return this.getAllPapers().filter((p) => p.status === status);
  }
  /** Get papers filtered by direction */
  getPapersByDirection(direction) {
    return this.getAllPapers().filter((p) => p.direction === direction);
  }
  /** Get papers matching filter options */
  getFilteredPapers(filters) {
    return this.getAllPapers().filter((p) => {
      if (filters.status !== "all" && p.status !== filters.status)
        return false;
      if (filters.direction !== "all" && p.direction !== filters.direction)
        return false;
      if (filters.search) {
        const q = filters.search.toLowerCase();
        const matchTitle = p.title.toLowerCase().includes(q);
        const matchAuthor = p.authors.some((a) => a.toLowerCase().includes(q));
        if (!matchTitle && !matchAuthor)
          return false;
      }
      return true;
    });
  }
  /** Get aggregate statistics */
  getStats() {
    var _a, _b;
    const papers = this.getAllPapers();
    const byStatus = {
      "to-read": 0,
      browsed: 0,
      "close-read": 0,
      reviewed: 0
    };
    const byDirection = {};
    for (const p of papers) {
      byStatus[p.status] = ((_a = byStatus[p.status]) != null ? _a : 0) + 1;
      if (p.direction) {
        byDirection[p.direction] = ((_b = byDirection[p.direction]) != null ? _b : 0) + 1;
      }
    }
    return {
      totalPapers: papers.length,
      byStatus,
      byDirection,
      assets: this.getAssetCounts()
    };
  }
  /** Get knowledge gaps */
  getKnowledgeGaps() {
    const papers = this.getAllPapers();
    const gaps = [];
    const missingSource = papers.filter((p) => !p.source).map((p) => ({ path: p.path, name: p.name, title: p.title }));
    if (missingSource.length > 0) {
      gaps.push({ type: "missing-source", label: "Missing Source Field", papers: missingSource, count: missingSource.length });
    }
    const noConcepts = papers.filter((p) => p.status === "browsed" && (!p.concepts || p.concepts.length === 0)).map((p) => ({ path: p.path, name: p.name, title: p.title }));
    if (noConcepts.length > 0) {
      gaps.push({ type: "no-concepts", label: "Browsed Without Concepts", papers: noConcepts, count: noConcepts.length });
    }
    const noAnnotation = papers.filter((p) => p.status === "close-read" && !p.annotation_path).map((p) => ({ path: p.path, name: p.name, title: p.title }));
    if (noAnnotation.length > 0) {
      gaps.push({ type: "no-annotation", label: "Close-Read Without Annotation", papers: noAnnotation, count: noAnnotation.length });
    }
    const byDirection = this.getDirectionPaperCounts();
    const needsSynthesisEntries = [];
    for (const [dir, count] of Object.entries(byDirection)) {
      if (count >= SYNTHESIS_THRESHOLD && !this.hasSynthesisForDirection(dir)) {
        needsSynthesisEntries.push({ path: "", name: dir, title: dir });
      }
    }
    if (needsSynthesisEntries.length > 0) {
      gaps.push({
        type: "needs-synthesis",
        label: "Directions Ready for Synthesis",
        papers: needsSynthesisEntries,
        count: needsSynthesisEntries.length
      });
    }
    return gaps;
  }
  /** Get recent activity items */
  getRecentActivity() {
    const papers = this.getAllPapers();
    const now = Date.now();
    const cutoff = now - RECENT_ACTIVITY_DAYS * 24 * 60 * 60 * 1e3;
    const activities = papers.filter((p) => p.mtime > cutoff || p.ctime > cutoff).map((p) => {
      const isNew = p.ctime > cutoff && Math.abs(p.ctime - p.mtime) < 6e4;
      return {
        type: isNew ? "created" : "modified",
        path: p.path,
        name: p.name,
        timestamp: Math.max(p.ctime, p.mtime),
        label: isNew ? `Added: ${p.title}` : `Updated: ${p.title}`
      };
    }).sort((a, b) => b.timestamp - a.timestamp).slice(0, MAX_ACTIVITY_ITEMS);
    return activities;
  }
  /** Get all unique directions */
  getAllDirections() {
    const dirs = /* @__PURE__ */ new Set();
    for (const p of this.getAllPapers()) {
      if (p.direction) {
        dirs.add(p.direction);
      }
    }
    return [...dirs].sort();
  }
  // ---- Private helpers ----
  /** Query papers via Dataview API */
  getPapersFromDataview() {
    var _a, _b;
    try {
      const api = (_a = this.dv) == null ? void 0 : _a.api;
      if (!api)
        return [];
      const pages = (_b = api.pages(ENTRIES_PATH)) != null ? _b : [];
      return pages.map((p) => this.toPaperEntry(p)).filter((e) => e !== null);
    } catch (e) {
      return [];
    }
  }
  /** Fallback: parse papers from MetadataCache */
  getPapersFromMetadata() {
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith("library/entries/"));
    return files.map((f) => this.parseFileFrontmatter(f)).filter((e) => e !== null);
  }
  /** Convert a Dataview page object to PaperEntry */
  toPaperEntry(page) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w;
    try {
      const status = (_a = this.parseStatus(page.status)) != null ? _a : "to-read";
      return {
        path: (_c = (_b = page.file) == null ? void 0 : _b.path) != null ? _c : "",
        name: (_e = (_d = page.file) == null ? void 0 : _d.name) != null ? _e : "",
        title: (_h = (_g = page.title) != null ? _g : (_f = page.file) == null ? void 0 : _f.name) != null ? _h : "",
        authors: (_i = page.authors) != null ? _i : [],
        venue: (_j = page.venue) != null ? _j : "",
        method: (_k = page.method) != null ? _k : "",
        task: (_l = page.task) != null ? _l : "",
        status,
        direction: (_m = page.direction) != null ? _m : "",
        source: (_n = page.source) != null ? _n : void 0,
        doi: (_o = page.doi) != null ? _o : void 0,
        annotation_path: (_p = page.annotation_path) != null ? _p : void 0,
        concepts: (_q = page.concepts) != null ? _q : [],
        datasets: (_r = page.datasets) != null ? _r : [],
        benchmarks: (_s = page.benchmarks) != null ? _s : [],
        mtime: (_u = (_t = page.file) == null ? void 0 : _t.mtime) != null ? _u : 0,
        ctime: (_w = (_v = page.file) == null ? void 0 : _v.ctime) != null ? _w : 0
      };
    } catch (e) {
      return null;
    }
  }
  /** Parse a file's frontmatter directly (fallback) */
  parseFileFrontmatter(file) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m;
    try {
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm)
        return null;
      const status = (_a = this.parseStatus(fm.status)) != null ? _a : "to-read";
      return {
        path: file.path,
        name: file.basename,
        title: (_b = fm.title) != null ? _b : file.basename,
        authors: (_c = fm.authors) != null ? _c : [],
        venue: (_d = fm.venue) != null ? _d : "",
        method: (_e = fm.method) != null ? _e : "",
        task: (_f = fm.task) != null ? _f : "",
        status,
        direction: (_g = fm.direction) != null ? _g : "",
        source: (_h = fm.source) != null ? _h : void 0,
        doi: (_i = fm.doi) != null ? _i : void 0,
        annotation_path: (_j = fm.annotation_path) != null ? _j : void 0,
        concepts: (_k = fm.concepts) != null ? _k : [],
        datasets: (_l = fm.datasets) != null ? _l : [],
        benchmarks: (_m = fm.benchmarks) != null ? _m : [],
        mtime: file.stat.mtime,
        ctime: file.stat.ctime
      };
    } catch (e) {
      return null;
    }
  }
  /** Parse status from a string field value */
  parseStatus(value) {
    if (!value || typeof value !== "string")
      return null;
    const s = value.trim().toLowerCase();
    if (ALL_STATUSES.includes(s))
      return s;
    return null;
  }
  /** Get paper counts per direction */
  getDirectionPaperCounts() {
    var _a;
    const counts = {};
    for (const p of this.getAllPapers()) {
      if (p.direction) {
        counts[p.direction] = ((_a = counts[p.direction]) != null ? _a : 0) + 1;
      }
    }
    return counts;
  }
  /** Check if a synthesis exists for a direction */
  hasSynthesisForDirection(direction) {
    var _a, _b, _c;
    try {
      if (this.dv) {
        const syntheses = (_b = (_a = this.dv.api) == null ? void 0 : _a.pages('"library/syntheses"')) != null ? _b : [];
        return syntheses.some((s) => s.direction === direction);
      }
      const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith("library/syntheses/"));
      for (const f of files) {
        const cache = this.app.metadataCache.getFileCache(f);
        if (((_c = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _c.direction) === direction)
          return true;
      }
    } catch (e) {
    }
    return false;
  }
  /** Get asset counts from Dataview or metadata */
  getAssetCounts() {
    var _a, _b, _c, _d;
    if (this.dv) {
      try {
        const api = this.dv.api;
        return {
          concepts: ((_a = api.pages(ASSET_PATHS.concepts)) != null ? _a : []).length,
          authors: ((_b = api.pages(ASSET_PATHS.authors)) != null ? _b : []).length,
          datasets: ((_c = api.pages(ASSET_PATHS.datasets)) != null ? _c : []).length,
          benchmarks: ((_d = api.pages(ASSET_PATHS.benchmarks)) != null ? _d : []).length
        };
      } catch (e) {
      }
    }
    const files = this.app.vault.getMarkdownFiles();
    return {
      concepts: files.filter((f) => f.path.startsWith("library/concepts/") && f.name !== "README.md").length,
      authors: files.filter((f) => f.path.startsWith("library/authors/") && f.name !== "README.md").length,
      datasets: files.filter((f) => f.path.startsWith("library/datasets/") && f.name !== "README.md").length,
      benchmarks: files.filter((f) => f.path.startsWith("library/benchmarks/") && f.name !== "README.md").length
    };
  }
};

// src/DashboardView.ts
var DashboardView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.stats = null;
    this.papers = [];
    this.filteredPapers = [];
    this.filters = { status: "all", direction: "all", search: "" };
    this.gaps = [];
    this.activities = [];
    this.directions = [];
    this.activeTab = "stats";
    this.refreshInterval = null;
    /** Vault event listeners for file changes */
    this.vaultEventRefs = [];
    /** Debounce timer for batched re-renders */
    this.debounceTimer = null;
    this.plugin = plugin;
    this.dataService = new DataService(plugin.app);
  }
  getViewType() {
    return VIEW_TYPE_DASHBOARD;
  }
  getDisplayText() {
    return "ReadR Dashboard";
  }
  getIcon() {
    return "bar-chart";
  }
  async onOpen() {
    this.refreshData();
    this.render();
    this.startAutoRefresh();
    this.registerVaultEvents();
  }
  async onClose() {
    this.stopAutoRefresh();
    this.unregisterVaultEvents();
  }
  /** Refresh all data from the data service */
  refreshData() {
    this.stats = this.dataService.getStats();
    this.papers = this.dataService.getAllPapers();
    this.filteredPapers = this.dataService.getFilteredPapers(this.filters);
    this.gaps = this.dataService.getKnowledgeGaps();
    this.activities = this.dataService.getRecentActivity();
    this.directions = this.dataService.getAllDirections();
  }
  /** Re-render the full view */
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("readr-dashboard-container");
    this.renderHeader(container);
    this.renderTabBar(container);
    const content = container.createDiv({ cls: "readr-dashboard-content" });
    this.renderContent(content);
    this.renderFooter(container);
  }
  // ---- Header ----
  renderHeader(container) {
    const header = container.createDiv({ cls: "readr-dashboard-header" });
    const titleRow = header.createDiv({ cls: "readr-dashboard-title-row" });
    const title = titleRow.createEl("h2", { text: "ReadR Dashboard" });
    title.addClass("readr-dashboard-title");
    const refreshBtn = titleRow.createEl("button", { cls: "readr-dashboard-refresh-btn" });
    (0, import_obsidian.setIcon)(refreshBtn, "refresh-cw");
    refreshBtn.setAttribute("aria-label", "Refresh");
    refreshBtn.addEventListener("click", () => {
      this.refreshData();
      this.render();
    });
  }
  // ---- Tab Bar ----
  renderTabBar(container) {
    const tabBar = container.createDiv({ cls: "readr-dashboard-tab-bar" });
    const tabs = [
      { key: "stats", icon: "bar-chart", label: "Stats" },
      { key: "papers", icon: "list", label: "Papers" },
      { key: "activity", icon: "activity", label: "Activity" }
    ];
    for (const tab of tabs) {
      const btn = tabBar.createEl("button", { cls: "readr-dashboard-tab" });
      if (tab.key === this.activeTab)
        btn.addClass("readr-dashboard-tab-active");
      (0, import_obsidian.setIcon)(btn, tab.icon);
      btn.createSpan({ text: ` ${tab.label}` });
      btn.addEventListener("click", () => {
        this.activeTab = tab.key;
        this.render();
      });
    }
  }
  // ---- Content ----
  renderContent(container) {
    switch (this.activeTab) {
      case "stats":
        this.renderStatsTab(container);
        break;
      case "papers":
        this.renderPapersTab(container);
        break;
      case "activity":
        this.renderActivityTab(container);
        break;
    }
  }
  // ---- Stats Tab ----
  renderStatsTab(container) {
    if (!this.stats) {
      container.createEl("p", { text: "No data available. Add papers to library/entries/ to get started." });
      return;
    }
    const summary = container.createDiv({ cls: "readr-dashboard-summary" });
    this.createStatCard(summary, "Total Papers", String(this.stats.totalPapers), "book-open");
    this.createStatCard(summary, "Concepts", String(this.stats.assets.concepts), "lightbulb");
    this.createStatCard(summary, "Authors", String(this.stats.assets.authors), "users");
    this.createStatCard(summary, "Datasets", String(this.stats.assets.datasets), "database");
    this.renderStatusChart(container);
    this.renderDirectionSection(container);
    this.renderGapsSection(container);
  }
  createStatCard(container, label, value, icon) {
    const card = container.createDiv({ cls: "readr-dashboard-stat-card" });
    const iconEl = card.createDiv({ cls: "readr-dashboard-stat-icon" });
    (0, import_obsidian.setIcon)(iconEl, icon);
    card.createDiv({ cls: "readr-dashboard-stat-value", text: value });
    card.createDiv({ cls: "readr-dashboard-stat-label", text: label });
  }
  renderStatusChart(container) {
    if (!this.stats)
      return;
    const section = container.createDiv({ cls: "readr-dashboard-section" });
    section.createEl("h3", { text: "Status Distribution", cls: "readr-dashboard-section-title" });
    const chartContainer = section.createDiv({ cls: "readr-dashboard-chart" });
    const canvas = chartContainer.createEl("canvas", { cls: "readr-dashboard-bar-chart" });
    canvas.width = chartContainer.clientWidth || 400;
    canvas.height = 200;
    requestAnimationFrame(() => {
      this.drawBarChart(canvas, this.stats);
    });
  }
  drawBarChart(canvas, stats) {
    var _a;
    const ctx = canvas.getContext("2d");
    if (!ctx)
      return;
    const dpr = window.devicePixelRatio || 1;
    const rect = canvas.getBoundingClientRect();
    canvas.width = rect.width * dpr;
    canvas.height = rect.height * dpr;
    ctx.scale(dpr, dpr);
    const w = rect.width;
    const h = rect.height;
    const max = Math.max(1, ...Object.values(stats.byStatus));
    const barCount = ALL_STATUSES.length;
    const barWidth = Math.min(60, (w - 40) / barCount - 16);
    const gap = 16;
    const totalBarsWidth = barCount * barWidth + (barCount - 1) * gap;
    const startX = (w - totalBarsWidth) / 2;
    const chartBottom = h - 30;
    const chartTop = 10;
    const chartHeight = chartBottom - chartTop;
    for (let i = 0; i < ALL_STATUSES.length; i++) {
      const status = ALL_STATUSES[i];
      const count = (_a = stats.byStatus[status]) != null ? _a : 0;
      const info = STATUS_MAP[status];
      const barH = max > 0 ? count / max * chartHeight : 0;
      const x = startX + i * (barWidth + gap);
      const y = chartBottom - barH;
      ctx.fillStyle = getComputedStyle(canvas).getPropertyValue("--interactive-accent") || "#6c8cff";
      ctx.globalAlpha = 0.6 + 0.4 * (1 - i / barCount);
      this.roundRect(ctx, x, y, barWidth, barH, 4);
      ctx.fill();
      ctx.globalAlpha = 1;
      ctx.fillStyle = getComputedStyle(canvas).getPropertyValue("--text-muted") || "#666";
      ctx.font = "11px sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(info.label, x + barWidth / 2, chartBottom + 16);
      ctx.fillStyle = getComputedStyle(canvas).getPropertyValue("--text-normal") || "#333";
      ctx.font = "bold 13px sans-serif";
      ctx.fillText(String(count), x + barWidth / 2, y - 4);
    }
  }
  roundRect(ctx, x, y, w, h, r) {
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.lineTo(x + w - r, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + r);
    ctx.lineTo(x + w, y + h);
    ctx.lineTo(x, y + h);
    ctx.lineTo(x, y + r);
    ctx.quadraticCurveTo(x, y, x + r, y);
    ctx.closePath();
  }
  renderDirectionSection(container) {
    if (!this.stats)
      return;
    const dirs = Object.entries(this.stats.byDirection).sort((a, b) => b[1] - a[1]);
    if (dirs.length === 0)
      return;
    const section = container.createDiv({ cls: "readr-dashboard-section" });
    section.createEl("h3", { text: "Research Directions", cls: "readr-dashboard-section-title" });
    const list = section.createDiv({ cls: "readr-dashboard-direction-list" });
    const max = Math.max(1, ...dirs.map(([, c]) => c));
    for (const [dir, count] of dirs) {
      const row = list.createDiv({ cls: "readr-dashboard-direction-row" });
      const label = row.createSpan({ cls: "readr-dashboard-direction-label", text: dir });
      const barOuter = row.createDiv({ cls: "readr-dashboard-direction-bar-outer" });
      const barInner = barOuter.createDiv({ cls: "readr-dashboard-direction-bar-inner" });
      barInner.style.width = `${count / max * 100}%`;
      barInner.style.background = "var(--interactive-accent)";
      row.createSpan({ cls: "readr-dashboard-direction-count", text: String(count) });
    }
  }
  renderGapsSection(container) {
    if (this.gaps.length === 0)
      return;
    const section = container.createDiv({ cls: "readr-dashboard-section" });
    section.createEl("h3", { text: "Knowledge Gaps", cls: "readr-dashboard-section-title" });
    for (const gap of this.gaps) {
      const item = section.createDiv({ cls: "readr-dashboard-gap-item" });
      const badge = item.createSpan({ cls: "readr-dashboard-gap-badge", text: String(gap.count) });
      item.createSpan({ text: ` ${gap.label}` });
    }
  }
  // ---- Papers Tab ----
  renderPapersTab(container) {
    this.renderFilterBar(container);
    const list = container.createDiv({ cls: "readr-dashboard-paper-list" });
    if (this.filteredPapers.length === 0) {
      list.createEl("p", { text: "No papers match the current filters.", cls: "readr-dashboard-empty" });
      return;
    }
    for (const paper of this.filteredPapers) {
      this.renderPaperItem(list, paper);
    }
    const countBar = container.createDiv({ cls: "readr-dashboard-count-bar" });
    countBar.createSpan({ text: `${this.filteredPapers.length} paper${this.filteredPapers.length !== 1 ? "s" : ""}` });
  }
  renderFilterBar(container) {
    const filterBar = container.createDiv({ cls: "readr-dashboard-filter-bar" });
    const statusGroup = filterBar.createDiv({ cls: "readr-dashboard-filter-group" });
    statusGroup.createSpan({ text: "Status: ", cls: "readr-dashboard-filter-label" });
    const allBtn = statusGroup.createEl("button", {
      cls: `readr-dashboard-filter-btn${this.filters.status === "all" ? " active" : ""}`,
      text: "All"
    });
    allBtn.addEventListener("click", () => {
      this.filters.status = "all";
      this.applyFilters();
    });
    for (const status of ALL_STATUSES) {
      const btn = statusGroup.createEl("button", {
        cls: `readr-dashboard-filter-btn${this.filters.status === status ? " active" : ""}`,
        text: STATUS_MAP[status].label
      });
      btn.addEventListener("click", () => {
        this.filters.status = status;
        this.applyFilters();
      });
    }
    if (this.directions.length > 0) {
      const dirGroup = filterBar.createDiv({ cls: "readr-dashboard-filter-group" });
      dirGroup.createSpan({ text: "Direction: ", cls: "readr-dashboard-filter-label" });
      const dirSelect = dirGroup.createEl("select", { cls: "readr-dashboard-filter-select" });
      const allOpt = dirSelect.createEl("option", { value: "all", text: "All" });
      if (this.filters.direction === "all")
        allOpt.selected = true;
      for (const dir of this.directions) {
        const opt = dirSelect.createEl("option", { value: dir, text: dir });
        if (this.filters.direction === dir)
          opt.selected = true;
      }
      dirSelect.addEventListener("change", () => {
        this.filters.direction = dirSelect.value;
        this.applyFilters();
      });
    }
    const searchGroup = filterBar.createDiv({ cls: "readr-dashboard-filter-group readr-dashboard-search-group" });
    const searchInput = searchGroup.createEl("input", {
      cls: "readr-dashboard-search-input",
      attr: { type: "text", placeholder: "Search title or author...", value: this.filters.search }
    });
    searchInput.addEventListener("input", () => {
      this.filters.search = searchInput.value;
      this.applyFilters();
    });
  }
  applyFilters() {
    this.filteredPapers = this.dataService.getFilteredPapers(this.filters);
    this.render();
  }
  renderPaperItem(container, paper) {
    const item = container.createDiv({ cls: "readr-dashboard-paper-item" });
    item.addEventListener("click", () => {
      this.openPaper(paper);
    });
    const info = STATUS_MAP[paper.status];
    const badge = item.createSpan({ cls: "readr-dashboard-status-badge", text: info.label });
    badge.style.background = info.color;
    const textContainer = item.createDiv({ cls: "readr-dashboard-paper-text" });
    textContainer.createDiv({ cls: "readr-dashboard-paper-title", text: paper.title });
    if (paper.authors.length > 0) {
      textContainer.createDiv({ cls: "readr-dashboard-paper-authors", text: paper.authors.join(", ") });
    }
    if (paper.venue) {
      textContainer.createDiv({ cls: "readr-dashboard-paper-venue", text: paper.venue });
    }
  }
  openPaper(paper) {
    const file = this.app.vault.getAbstractFileByPath(paper.path);
    if (file) {
      this.app.workspace.getLeaf(true).openFile(file);
    }
  }
  // ---- Activity Tab ----
  renderActivityTab(container) {
    const activitySection = container.createDiv({ cls: "readr-dashboard-section" });
    activitySection.createEl("h3", { text: "Recent Activity", cls: "readr-dashboard-section-title" });
    if (this.activities.length === 0) {
      activitySection.createEl("p", { text: "No recent activity in the last 7 days.", cls: "readr-dashboard-empty" });
    } else {
      const list = activitySection.createDiv({ cls: "readr-dashboard-activity-list" });
      for (const act of this.activities) {
        const item = list.createDiv({ cls: "readr-dashboard-activity-item" });
        item.addEventListener("click", () => {
          const file = this.app.vault.getAbstractFileByPath(act.path);
          if (file)
            this.app.workspace.getLeaf(true).openFile(file);
        });
        const icon = item.createSpan({ cls: "readr-dashboard-activity-icon" });
        (0, import_obsidian.setIcon)(icon, act.type === "created" ? "plus-circle" : "edit");
        item.createSpan({ cls: "readr-dashboard-activity-label", text: act.label });
        item.createSpan({ cls: "readr-dashboard-activity-time", text: this.formatTimeAgo(act.timestamp) });
      }
    }
    const gapsSection = container.createDiv({ cls: "readr-dashboard-section" });
    gapsSection.createEl("h3", { text: "Todo / Reminders", cls: "readr-dashboard-section-title" });
    if (this.gaps.length === 0) {
      gapsSection.createEl("p", { text: "No pending todos. Everything looks good!", cls: "readr-dashboard-empty" });
    } else {
      for (const gap of this.gaps) {
        const gapItem = gapsSection.createDiv({ cls: "readr-dashboard-gap-item" });
        const badge = gapItem.createSpan({ cls: "readr-dashboard-gap-badge", text: String(gap.count) });
        gapItem.createSpan({ text: ` ${gap.label}` });
        gapItem.addEventListener("click", () => {
          this.filters.status = "all";
          if (gap.type === "no-concepts")
            this.filters.status = "browsed";
          if (gap.type === "no-annotation")
            this.filters.status = "close-read";
          this.activeTab = "papers";
          this.render();
        });
      }
    }
  }
  // ---- Footer ----
  renderFooter(container) {
    const footer = container.createDiv({ cls: "readr-dashboard-footer" });
    const dataSource = this.dataService.hasDataview ? "Dataview" : "MetadataCache (fallback)";
    footer.createSpan({ text: `Data source: ${dataSource}`, cls: "readr-dashboard-footer-text" });
  }
  // ---- Helpers ----
  formatTimeAgo(timestamp) {
    const diff = Date.now() - timestamp;
    const mins = Math.floor(diff / 6e4);
    if (mins < 1)
      return "just now";
    if (mins < 60)
      return `${mins}m ago`;
    const hours = Math.floor(mins / 60);
    if (hours < 24)
      return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    return `${days}d ago`;
  }
  startAutoRefresh() {
    this.stopAutoRefresh();
    this.refreshInterval = window.setInterval(() => {
      const oldStats = this.stats;
      this.refreshData();
      if (JSON.stringify(oldStats) !== JSON.stringify(this.stats)) {
        this.render();
      }
    }, this.plugin.settings.refreshInterval);
  }
  stopAutoRefresh() {
    if (this.refreshInterval !== null) {
      clearInterval(this.refreshInterval);
      this.refreshInterval = null;
    }
  }
  /** Register vault event listeners for real-time updates */
  registerVaultEvents() {
    const vault = this.app.vault;
    const isEntryFile = (file) => file.path.startsWith("library/entries/") && file.extension === "md";
    const scheduleRefresh = () => {
      if (this.debounceTimer !== null) {
        clearTimeout(this.debounceTimer);
      }
      this.debounceTimer = window.setTimeout(() => {
        this.debounceTimer = null;
        this.refreshData();
        this.render();
      }, 300);
    };
    const createRef = vault.on("create", (file) => {
      if (isEntryFile(file))
        scheduleRefresh();
    });
    this.vaultEventRefs.push({ event: "create", ref: createRef });
    const modifyRef = vault.on("modify", (file) => {
      if (isEntryFile(file))
        scheduleRefresh();
    });
    this.vaultEventRefs.push({ event: "modify", ref: modifyRef });
    const deleteRef = vault.on("delete", (file) => {
      if (isEntryFile(file))
        scheduleRefresh();
    });
    this.vaultEventRefs.push({ event: "delete", ref: deleteRef });
    const metadataRef = this.app.metadataCache.on("changed", (file) => {
      if (isEntryFile(file))
        scheduleRefresh();
    });
    this.vaultEventRefs.push({ event: "metadata-changed", ref: metadataRef });
  }
  /** Unregister vault event listeners */
  unregisterVaultEvents() {
    const vault = this.app.vault;
    for (const { event, ref } of this.vaultEventRefs) {
      vault.off(event, ref);
    }
    this.vaultEventRefs = [];
    if (this.debounceTimer !== null) {
      clearTimeout(this.debounceTimer);
      this.debounceTimer = null;
    }
  }
};

// src/DashboardSettingTab.ts
var import_obsidian2 = require("obsidian");
var DashboardSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ReadR Dashboard Settings" });
    new import_obsidian2.Setting(containerEl).setName("Auto-refresh interval").setDesc("How often the dashboard refreshes data (in seconds). Minimum 30s.").addText(
      (text) => text.setPlaceholder("300").setValue(String(Math.round(this.plugin.settings.refreshInterval / 1e3))).onChange(async (value) => {
        const secs = Math.max(30, parseInt(value) || 300);
        this.plugin.settings.refreshInterval = secs * 1e3;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default tab").setDesc("Which tab to show when the dashboard opens.").addDropdown((dropdown) => {
      dropdown.addOption("stats", "Stats & Charts").addOption("papers", "Papers & Filters").addOption("activity", "Activity & Todos").setValue(this.plugin.settings.defaultTab).onChange(async (value) => {
        this.plugin.settings.defaultTab = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Synthesis threshold").setDesc("Minimum papers in a direction to suggest a synthesis.").addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.synthesisThreshold)).onChange(async (value) => {
        const n = Math.max(1, parseInt(value) || 3);
        this.plugin.settings.synthesisThreshold = n;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("hr");
    containerEl.createEl("p", {
      text: "ReadR Dashboard v1.0.0 \u2014 Data source: Dataview API (with MetadataCache fallback).",
      cls: "readr-dashboard-settings-info"
    });
    containerEl.createEl("p", {
      text: "Papers are read from library/entries/. Assets from library/concepts/, library/authors/, library/datasets/, library/benchmarks/.",
      cls: "readr-dashboard-settings-info"
    });
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  refreshInterval: DEFAULT_REFRESH_INTERVAL,
  defaultTab: "stats",
  synthesisThreshold: 3
};
var ReadRDashboardPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.dashboardView = null;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_DASHBOARD, (leaf) => {
      this.dashboardView = new DashboardView(leaf, this);
      return this.dashboardView;
    });
    this.addRibbonIcon("bar-chart", "Open ReadR Dashboard", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-readr-dashboard",
      name: "Open ReadR Dashboard",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "new-paper-entry",
      name: "New Paper Entry",
      callback: () => this.createNewPaper()
    });
    this.addCommand({
      id: "refresh-readr-dashboard",
      name: "Refresh ReadR Dashboard",
      callback: () => {
        if (this.dashboardView) {
          this.dashboardView.refreshData();
          this.dashboardView.render();
          new import_obsidian3.Notice("ReadR Dashboard refreshed");
        }
      }
    });
    this.addSettingTab(new DashboardSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.activateView();
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_DASHBOARD);
  }
  /** Activate the dashboard view */
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_DASHBOARD).first();
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return;
      leaf = rightLeaf;
      await leaf.setViewState({ type: VIEW_TYPE_DASHBOARD, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  /** Create a new paper entry from template */
  async createNewPaper() {
    const templateFile = this.app.vault.getAbstractFileByPath("library/_template/library-entry.md");
    if (!(templateFile instanceof import_obsidian3.TFile)) {
      new import_obsidian3.Notice("Template not found at library/_template/library-entry.md");
      return;
    }
    const templateContent = await this.app.vault.read(templateFile);
    const now = new Date();
    const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
    const fileName = `New Paper (${dateStr}).md`;
    const filePath = `library/entries/your_direction/${fileName}`;
    try {
      await this.app.vault.create(filePath, templateContent);
      const leaf = this.app.workspace.getLeaf(true);
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian3.TFile) {
        await leaf.openFile(file);
        new import_obsidian3.Notice("New paper entry created");
      }
    } catch (err) {
      new import_obsidian3.Notice(`Failed to create paper entry: ${err}`);
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.dashboardView) {
      this.dashboardView.render();
    }
  }
};
